Shell.boot("platform",{title:"Repository Observatory",keys:[["⌘K","repository"],["1–3","lens"],["S","scaffold"]]});
IdolShell.crumbs([{label:"platform"},{label:"repositories"}]);
const api="/v1/repository/browser/";const state={observations:[],scaffolds:[],selected:null,lens:"inventory",scaffold:null,file:0};
const $=(id)=>document.getElementById(id);const repo=$("repo"),history=$("history"),workspace=$("workspace"),rail=$("rail");
function escapeHtml(value){return String(value??"").replace(/[&<>\"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
async function request(path,init={}){const response=await fetch(api+path,{...init,headers:{accept:"application/json","content-type":"application/json","x-idol-request":"browser",...(init.headers||{})}});let body={};try{body=await response.json();}catch{}if(!response.ok)throw new Error(body.detail||body.error||`request answered ${response.status}`);return body;}
function toast(message){const node=document.createElement("div");node.className="toast";node.textContent=message;document.body.append(node);setTimeout(()=>node.remove(),1800);}
function setView(view){repo.dataset.mobile=view;document.querySelectorAll(".mobile-nav button").forEach((b)=>b.classList.toggle("here",b.dataset.view===view));}
function deepLink(kind,id){history.replaceState(null,"",`/repo/${kind}/${encodeURIComponent(id)}`);}
function selectedIdFromPath(){const m=/^\/repo\/(observation|scaffold)\/([^/]+)\/?$/.exec(location.pathname);if(!m)return null;try{return{kind:m[1],id:decodeURIComponent(m[2])};}catch{return null;}}
function fmtBytes(n){n=Number(n||0);return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KiB`:`${(n/1048576).toFixed(1)} MiB`;}
function renderHistory(){history.innerHTML="";if(!state.observations.length){history.innerHTML='<div class="empty">No observations yet. Public metadata is fetched only when you submit a repository.</div>';return;}for(const item of state.observations){const b=document.createElement("button");b.className=`observation${state.selected?.id===item.id?" here":""}`;b.innerHTML=`<span class="coord">${escapeHtml(item.coordinate)}</span><span class="meta"><span>${escapeHtml(item.resolved_revision?.slice(0,12))}</span><span>${item.inventory?.file_count||0} files</span><span>${escapeHtml(item.created_at?.slice(0,10))}</span></span>`;b.onclick=()=>selectObservation(item.id);history.append(b);}}
function metric(label,value){return `<div class="metric"><label>${escapeHtml(label)}</label><strong>${escapeHtml(value||"not observed")}</strong></div>`;}
function row(key,value,mono=false){return `<div class="row"><div class="key">${escapeHtml(key)}</div><div class="value${mono?" identity":""}">${escapeHtml(value||"not observed")}</div></div>`;}
function chips(values){return `<div class="chips">${(values?.length?values:["none observed"]).map(v=>`<span class="chip">${escapeHtml(v)}</span>`).join("")}</div>`;}
function current(){return state.selected;}
function renderRail(){const item=current();if(!item){rail.innerHTML='<div class="empty">No exact record selected.</div>';return;}rail.innerHTML=`<div class="factcard"><label>observation</label><div>${escapeHtml(item.id)}</div></div><div class="factcard"><label>provider coordinate</label><div>${escapeHtml(item.coordinate)}</div></div><div class="factcard"><label>resolved revision</label><div>${escapeHtml(item.resolved_revision)}</div></div><div class="factcard"><label>semantic identity</label><div>${escapeHtml(item.semantic_id??"not published")}</div></div><div class="factcard"><label>world authority</label><div>not granted</div></div><div class="factcard"><label>source transfer</label><div>tree metadata only</div></div><div class="factcard"><label>repository mutation</label><div>false</div></div>`;}
function renderInventory(item){const inv=item.inventory||{};return `<div class="metric-grid">${metric("resolved revision",item.resolved_revision)}${metric("files",String(inv.file_count||0))}${metric("known bytes",fmtBytes(inv.bytes?.known))}${metric("tree",inv.truncated?"truncated / incomplete":"provider projection complete")}${metric("default branch",item.default_branch)}${metric("requested ref",item.requested_ref)}</div><section class="section"><div class="section-head"><h2>Language candidates</h2></div><div style="padding:14px">${chips(Object.entries(inv.languages||{}).map(([name,files])=>`${name} · ${files}`))}</div></section><section class="section"><div class="section-head"><h2>Build and workflow evidence</h2></div><div class="rows">${row("build systems",(inv.build_systems||[]).map(x=>x.id).join(", "))}${row("test evidence",(inv.tests||[]).join(", "))}${row("benchmark evidence",(inv.benchmarks||[]).join(", "))}${row("CI",(inv.ci||[]).join(", "))}</div></section><section class="section"><div class="section-head"><h2>Observed paths</h2></div><pre>${escapeHtml((inv.paths||[]).join("\n"))}</pre></section>`;}
function renderWorld(item){const world=item.candidate_world||{};return `<section class="section"><div class="section-head"><h2>Candidate foreign-origin world</h2></div><div class="rows">${row("identity status",world.identity_status)}${row("semantic identity",world.semantic_id??"not published",true)}${row("origin",world.origin,true)}${row("repository",item.coordinate,true)}${row("revision",item.resolved_revision,true)}</div></section><section class="section"><div class="section-head"><h2>Uncertainty</h2></div><div style="padding:14px">${chips((world.uncertainty||[]).map(x=>typeof x==="string"?x:(x.fact?`${x.fact}: ${x.detail}`:JSON.stringify(x))))}</div></section><section class="section boundary"><strong>Authority boundary</strong><p class="muted">This observation describes provider metadata and path evidence. It does not prove declarations, behavior, ownership, effects, compatibility, equivalence, or world authority. Those remain unresolved until source and executed evidence are admitted.</p></section>`;}
function capabilityControls(){const all=["authority","build","test","bench","ci","graph"];return `<div class="capabilities">${all.map(x=>`<label class="capability"><input type="checkbox" value="${x}" ${["authority","ci","graph"].includes(x)?"checked":""}>${x}</label>`).join("")}</div>`;}
function renderScaffold(item){if(!state.scaffold)return `<div class="scaffold-controls"><section class="section"><div class="section-head"><h2>Choose projected capabilities</h2></div><div style="padding:15px">${capabilityControls()}<p class="muted" style="margin-top:12px">The result is a review-only patch. It does not create a branch, commit, pull request, or world.</p><div class="actions"><button class="primary" id="generate">Generate preview</button></div></div></section></div>`;const s=state.scaffold;const files=s.files||[];const selected=files[state.file]||files[0];return `<section class="section boundary"><strong>${escapeHtml(s.status)}</strong><p class="muted">repository_written: ${String(s.repository_written)} · semantic identity: not published</p></section><section class="section"><div class="section-head"><h2>Generated files</h2><span class="spacer"></span><span class="identity">${files.length}</span></div><div class="filetabs">${files.map((f,i)=>`<button class="filetab${i===state.file?" here":""}" data-file="${i}">${escapeHtml(f.path)}</button>`).join("")}</div><pre>${escapeHtml(selected?.content||"")}</pre></section><section class="section"><div class="section-head"><h2>Unified patch</h2></div><pre>${escapeHtml(s.patch||"")}</pre></section><div class="actions"><button id="download-patch">Download patch</button><button id="download-json">Download JSON</button></div>`;}
function renderWorkspace(){const item=current();if(!item){workspace.innerHTML='<div class="empty">Select or observe a repository.</div>';renderRail();return;}workspace.innerHTML=`<article class="work-inner"><div class="kicker"><span class="pill">${escapeHtml(item.provider)}</span><span>exact public revision</span></div><h1 class="title">${escapeHtml(item.namespace)}/${escapeHtml(item.repository)}</h1><p class="lede">${escapeHtml(item.summary||"Public repository metadata and tree evidence resolved to one exact provider revision.")}</p><div class="tabs"><button class="tabx${state.lens==="inventory"?" here":""}" data-lens="inventory">Inventory</button><button class="tabx${state.lens==="world"?" here":""}" data-lens="world">Candidate world</button><button class="tabx${state.lens==="scaffold"?" here":""}" data-lens="scaffold">Scaffold</button></div><div class="panel">${state.lens==="inventory"?renderInventory(item):state.lens==="world"?renderWorld(item):renderScaffold(item)}</div></article>`;workspace.querySelectorAll("[data-lens]").forEach(b=>b.onclick=()=>{state.lens=b.dataset.lens;renderWorkspace();if(innerWidth<700)setView("workspace")});workspace.querySelectorAll("[data-file]").forEach(b=>b.onclick=()=>{state.file=Number(b.dataset.file);renderWorkspace()});const generate=$("generate");if(generate)generate.onclick=generateScaffold;const patch=$("download-patch");if(patch)patch.onclick=()=>download(`${item.repository}-idol.patch`,state.scaffold.patch,"text/x-diff");const json=$("download-json");if(json)json.onclick=()=>download(`${item.repository}-idol-scaffold.json`,JSON.stringify(state.scaffold,null,2),"application/json");renderRail();}
async function selectObservation(id){const item=await request(`observations/${encodeURIComponent(id)}`);state.selected=item;state.scaffold=null;state.file=0;deepLink("observation",id);renderHistory();renderWorkspace();if(innerWidth<700)setView("workspace");}
async function selectScaffold(id){const s=await request(`scaffolds/${encodeURIComponent(id)}`);state.scaffold=s;state.file=0;const item=await request(`observations/${encodeURIComponent(s.observation_id)}`);state.selected=item;state.lens="scaffold";deepLink("scaffold",id);renderHistory();renderWorkspace();if(innerWidth<700)setView("workspace");}
async function generateScaffold(){const caps=[...document.querySelectorAll('.capability input:checked')].map(x=>x.value);state.scaffold=await request(`observations/${encodeURIComponent(state.selected.id)}/scaffolds`,{method:"POST",body:JSON.stringify({capabilities:caps})});state.file=0;deepLink("scaffold",state.scaffold.id);renderWorkspace();toast("Scaffold preview generated — repository unchanged");}
function download(name,content,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);}
async function load(){const [o,s]=await Promise.all([request("observations"),request("scaffolds")]);state.observations=o.observations||[];state.scaffolds=s.scaffolds||[];renderHistory();const deep=selectedIdFromPath();if(deep?.kind==="scaffold")await selectScaffold(deep.id);else if(deep?.kind==="observation")await selectObservation(deep.id);else if(state.observations[0])await selectObservation(state.observations[0].id);else renderWorkspace();}
$("observe-form").onsubmit=async(event)=>{event.preventDefault();const status=$("observe-status");status.textContent="Resolving exact public revision…";try{const item=await request("observe",{method:"POST",body:JSON.stringify({url:$("repo-url").value,ref:$("repo-ref").value})});state.observations.unshift(item);status.textContent="Observed provider metadata and tree facts; no source content or repository write.";await selectObservation(item.id);toast("Exact revision observed");}catch(error){status.textContent=error.message;}};
document.querySelectorAll(".mobile-nav button").forEach(b=>b.onclick=()=>setView(b.dataset.view));document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("repo-url").focus()}if(/[123]/.test(e.key)&&document.activeElement.tagName!=="INPUT"){state.lens=["inventory","world","scaffold"][Number(e.key)-1];renderWorkspace()}if(e.key.toLowerCase()==="s"&&state.selected){state.lens="scaffold";renderWorkspace();}});
load().catch(error=>{history.innerHTML=`<div class="empty">${escapeHtml(error.message)}</div>`;workspace.innerHTML='<div class="empty">Repository Observatory refused closed.</div>';});
