const SCHEMA = "idol.browser.workspace.v1";
const MAX_FILES = 256;
const MAX_FILE_BYTES = 2 * 1024 * 1024;
const MAX_SNAPSHOT_BYTES = 8 * 1024 * 1024;
const MAX_NAME = 120;
const MAX_PATH = 1024;
const BROWSER_DATABASE = "idol-browser-workspaces-v1";
const BROWSER_STORE = "workspace";
const encoder = new TextEncoder();
function bytes(value){return encoder.encode(String(value)).byteLength;}
function instant(value){if(typeof value==="function")return String(value());if(value!==undefined)return String(value);return new Date().toISOString();}
function defaultId(){if(globalThis.crypto?.randomUUID)return globalThis.crypto.randomUUID();const random=globalThis.crypto?.getRandomValues?[...globalThis.crypto.getRandomValues(new Uint8Array(16))]:Array.from({length:16},()=>Math.floor(Math.random()*256));return random.map((value)=>value.toString(16).padStart(2,"0")).join("");}
function idFrom(factory){const produced=(factory||defaultId)();if(typeof produced!=="string"&&typeof produced!=="number")throw new Error("invalid workspace identity");const id=String(produced).trim();if(!id||id.length>160||/[\u0000-\u001f\u007f]/.test(id))throw new Error("invalid workspace identity");return id;}
function validName(value){const name=String(value||"").trim();if(!name||name.length>MAX_NAME||/[\u0000-\u001f\u007f]/.test(name))throw new Error("invalid workspace name");return name;}
export function validateWorkspacePath(value){const path=String(value??"");if(!path||path.length>MAX_PATH||path.startsWith("/")||path.includes("\\")||path.includes("\0"))throw new Error("invalid workspace path");const parts=path.split("/");if(parts.some((part)=>!part||part==="."||part===".."||part.length>255||/[\u0000-\u001f\u007f]/.test(part)))throw new Error("invalid workspace path");return path;}
function validSource(value){const source=String(value??"");const size=bytes(source);if(size>MAX_FILE_BYTES)throw new Error(`file exceeds ${MAX_FILE_BYTES} bytes`);return source;}
function fileRecord(candidate){if(!candidate||typeof candidate!=="object")throw new Error("invalid workspace file");return{id:idFrom(()=>candidate.id),path:validateWorkspacePath(candidate.path),source:validSource(candidate.source)};}
function freezeFile(file){return Object.freeze({id:file.id,path:file.path,source:file.source});}
function freezeWorkspace(candidate){const files=candidate.files.map(freezeFile);return Object.freeze({schema:SCHEMA,id:candidate.id,name:candidate.name,active:candidate.active,created_at:candidate.created_at,updated_at:candidate.updated_at,files:Object.freeze(files)});}
function assertWorkspace(candidate){if(!candidate||typeof candidate!=="object"||candidate.schema!==SCHEMA)throw new Error("unsupported workspace schema");const id=idFrom(()=>candidate.id);const name=validName(candidate.name);const createdAt=String(candidate.created_at||"");const updatedAt=String(candidate.updated_at||"");if(!createdAt||!updatedAt)throw new Error("workspace timestamps are required");if(!Array.isArray(candidate.files))throw new Error("workspace files must be an array");if(candidate.files.length>MAX_FILES)throw new Error(`workspace file limit is ${MAX_FILES}`);const files=candidate.files.map(fileRecord);const ids=new Set();const paths=new Set();for(const file of files){if(ids.has(file.id))throw new Error("duplicate workspace file identity");if(paths.has(file.path))throw new Error(`workspace path already exists: ${file.path}`);ids.add(file.id);paths.add(file.path);}const active=candidate.active===null||candidate.active===undefined?null:String(candidate.active);if(active!==null&&!ids.has(active))throw new Error("active file is not present");return{schema:SCHEMA,id,name,active,created_at:createdAt,updated_at:updatedAt,files};}
function update(workspace,changes,now){const current=assertWorkspace(workspace);return freezeWorkspace({...current,...changes,updated_at:instant(now)});}
function findFile(workspace,fileId){const id=String(fileId||"");const index=workspace.files.findIndex((file)=>file.id===id);if(index<0)throw new Error(`workspace file not found: ${id}`);return{id,index};}
export function createWorkspace(name,{idFactory,now}={}){const time=instant(now);return freezeWorkspace({schema:SCHEMA,id:idFrom(idFactory),name:validName(name),active:null,created_at:time,updated_at:time,files:[]});}
export function addFile(workspace,path,source="",{idFactory,now}={}){const current=assertWorkspace(workspace);if(current.files.length>=MAX_FILES)throw new Error(`workspace file limit is ${MAX_FILES}`);const admittedPath=validateWorkspacePath(path);if(current.files.some((file)=>file.path===admittedPath))throw new Error(`workspace path already exists: ${admittedPath}`);const file={id:idFrom(idFactory),path:admittedPath,source:validSource(source)};if(current.files.some((candidate)=>candidate.id===file.id))throw new Error("duplicate workspace file identity");return update(current,{files:[...current.files,file],active:current.active||file.id},now);}
export function writeFile(workspace,fileId,source,{now}={}){const current=assertWorkspace(workspace);const{index}=findFile(current,fileId);const files=current.files.map((file,position)=>position===index?{...file,source:validSource(source)}:file);return update(current,{files},now);}
export function renameFile(workspace,fileId,path,{now}={}){const current=assertWorkspace(workspace);const{index}=findFile(current,fileId);const admittedPath=validateWorkspacePath(path);if(current.files.some((file,position)=>position!==index&&file.path===admittedPath))throw new Error(`workspace path already exists: ${admittedPath}`);const files=current.files.map((file,position)=>position===index?{...file,path:admittedPath}:file);return update(current,{files},now);}
export function removeFile(workspace,fileId,{now}={}){const current=assertWorkspace(workspace);const{index,id}=findFile(current,fileId);const files=current.files.filter((_,position)=>position!==index);let active=current.active;if(active===id){const replacement=files[Math.min(index,files.length-1)]||files[0]||null;active=replacement?.id||null;}return update(current,{files,active},now);}
export function selectFile(workspace,fileId,{now}={}){const current=assertWorkspace(workspace);const{id}=findFile(current,fileId);return update(current,{active:id},now);}
export function workspaceSnapshot(workspace){const current=assertWorkspace(workspace);const snapshot={schema:SCHEMA,id:current.id,name:current.name,active:current.active,created_at:current.created_at,updated_at:current.updated_at,files:[...current.files].sort((left,right)=>left.path.localeCompare(right.path)||left.id.localeCompare(right.id)).map((file)=>({id:file.id,path:file.path,source:file.source}))};const size=bytes(JSON.stringify(snapshot));if(size>MAX_SNAPSHOT_BYTES)throw new Error(`snapshot exceeds ${MAX_SNAPSHOT_BYTES} bytes`);return snapshot;}
export function restoreWorkspace(value){const candidate=typeof value==="string"?JSON.parse(value):value;const size=bytes(JSON.stringify(candidate));if(size>MAX_SNAPSHOT_BYTES)throw new Error(`snapshot exceeds ${MAX_SNAPSHOT_BYTES} bytes`);const admitted=assertWorkspace(candidate);return freezeWorkspace({...admitted,files:[...admitted.files].sort((left,right)=>left.path.localeCompare(right.path)||left.id.localeCompare(right.id))});}
export class MemoryWorkspaceStore{constructor(){this.snapshots=new Map();}async save(workspace){const snapshot=workspaceSnapshot(workspace);this.snapshots.set(snapshot.id,structuredClone(snapshot));return restoreWorkspace(snapshot);}async load(workspaceId){const snapshot=this.snapshots.get(String(workspaceId));return snapshot?restoreWorkspace(structuredClone(snapshot)):null;}async list(){return[...this.snapshots.values()].map((snapshot)=>restoreWorkspace(structuredClone(snapshot))).sort((left,right)=>right.updated_at.localeCompare(left.updated_at)||left.id.localeCompare(right.id));}async delete(workspaceId){return this.snapshots.delete(String(workspaceId));}}
function requestResult(request){return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error("IndexedDB request failed"));});}
function transactionResult(transaction){return new Promise((resolve,reject)=>{transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error||new Error("IndexedDB transaction failed"));transaction.onabort=()=>reject(transaction.error||new Error("IndexedDB transaction aborted"));});}
function openBrowserDatabase(indexedDB,databaseName){return new Promise((resolve,reject)=>{const opening=indexedDB.open(databaseName,1);opening.onupgradeneeded=()=>{const database=opening.result;if(!database.objectStoreNames.contains(BROWSER_STORE))database.createObjectStore(BROWSER_STORE,{keyPath:"id"});};opening.onsuccess=()=>resolve(opening.result);opening.onerror=()=>reject(opening.error||new Error("IndexedDB open failed"));opening.onblocked=()=>reject(new Error("IndexedDB open blocked"));});}
export class BrowserWorkspaceStore{constructor(database){if(!database?.transaction)throw new Error("invalid IndexedDB database");this.database=database;}async operate(mode,operation){const transaction=this.database.transaction(BROWSER_STORE,mode);const done=transactionResult(transaction);const request=operation(transaction.objectStore(BROWSER_STORE));const result=await requestResult(request);await done;return result;}async save(workspace){const snapshot=workspaceSnapshot(workspace);await this.operate("readwrite",(store)=>store.put(snapshot));return restoreWorkspace(snapshot);}async load(workspaceId){const snapshot=await this.operate("readonly",(store)=>store.get(String(workspaceId)));return snapshot===undefined||snapshot===null?null:restoreWorkspace(snapshot);}async list(){const snapshots=await this.operate("readonly",(store)=>store.getAll());if(!Array.isArray(snapshots))throw new Error("IndexedDB workspace list is invalid");return snapshots.map(restoreWorkspace).sort((left,right)=>right.updated_at.localeCompare(left.updated_at)||left.id.localeCompare(right.id));}async delete(workspaceId){await this.operate("readwrite",(store)=>store.delete(String(workspaceId)));return true;}close(){this.database.close?.();}}
export async function createBrowserWorkspaceStore({indexedDB=globalThis.indexedDB,databaseName=BROWSER_DATABASE}={}){if(!indexedDB?.open)return{status:"storage-unavailable",store:null,reason:"IndexedDB is not available"};try{const database=await openBrowserDatabase(indexedDB,String(databaseName||BROWSER_DATABASE));return{status:"available",store:new BrowserWorkspaceStore(database),reason:null};}catch(error){return{status:"storage-unavailable",store:null,reason:error instanceof Error?error.message:String(error)};}}
export const WORKSPACE_LIMITS=Object.freeze({max_files:MAX_FILES,max_file_bytes:MAX_FILE_BYTES,max_snapshot_bytes:MAX_SNAPSHOT_BYTES});
