import { access, cp, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { normaliseForeignWorld } from "../shared/foreign.js";
const here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,".."),dist=join(root,"dist");const authorityPin=JSON.parse(await readFile(join(root,"runtime","authority.json"),"utf8"));const authority=authorityPin.language.commit,native=authorityPin.native.commit,commit=process.env.GITHUB_SHA||process.env.IDOL_WEB_COMMIT||"development";
async function exists(path){try{await access(path,constants.R_OK);return true;}catch{return false;}}
function requireText(value,label){if(typeof value!=="string"||!value.trim())throw new Error(`${label} must be a nonempty string`);return value.trim();}
function validateForeignSource(source){if(!source||source.schema!=="idol.web.foreign.source.v1")throw new Error("foreign source schema mismatch");const revision=requireText(source.revision,"foreign revision");if(!Array.isArray(source.worlds)||!source.worlds.length)throw new Error("foreign source requires worlds[]");if(!Array.isArray(source.import_kinds)||!source.import_kinds.length)throw new Error("foreign source requires import_kinds[]");const worlds=source.worlds.map((candidate,index)=>{requireText(candidate?.slug,`foreign world ${index} slug`);requireText(candidate?.name,`foreign world ${index} name`);requireText(candidate?.version,`foreign world ${index} version`);if(candidate.semantic_id!==null)throw new Error(`foreign world ${candidate.slug} must not fabricate semantic_id`);if(candidate.identity_status!=="not-published")throw new Error(`foreign world ${candidate.slug} identity_status must be not-published`);requireText(candidate?.provenance?.origin?.family,`foreign world ${candidate.slug} origin family`);if(!Array.isArray(candidate.uncertainty)||!candidate.uncertainty.length)throw new Error(`foreign world ${candidate.slug} requires uncertainty`);if(!Array.isArray(candidate.projections)||!candidate.projections.length)throw new Error(`foreign world ${candidate.slug} requires projections`);for(const projection of candidate.projections){requireText(projection.id,`foreign world ${candidate.slug} projection id`);requireText(projection.target,`foreign world ${candidate.slug} projection target`);requireText(projection.status,`foreign world ${candidate.slug} projection status`);if(!projection.obligations||typeof projection.obligations!=="object")throw new Error(`projection ${projection.id} requires obligations`);if(!projection.evidence||typeof projection.evidence!=="object")throw new Error(`projection ${projection.id} requires evidence`);if(!projection.refusal||typeof projection.refusal!=="object")throw new Error(`projection ${projection.id} requires refusal`);if(projection.status==="available"){if(!projection.artifact?.sha256||projection.evidence.status!=="verified")throw new Error(`available projection ${projection.id} requires signed artifact evidence`);}else if(Object.hasOwn(projection,"copy_command"))throw new Error(`unavailable projection ${projection.id} cannot publish a copy command`);}return normaliseForeignWorld(candidate);});const kinds=source.import_kinds.map((record,index)=>{const kind=requireText(record?.kind,`import kind ${index}`);for(const field of["stages","required_grants","missing_facts","refusals"])if(!Array.isArray(record[field])||!record[field].length)throw new Error(`import kind ${kind} requires ${field}[]`);return record;});return{revision,worlds,import_kinds:kinds};}
function injectBeforeModule(html,scripts,label){const marker=/<script type="module">/i;if(!marker.test(html))throw new Error(`${label} has no module entrypoint`);return html.replace(marker,`${scripts.join("\n")}\n<script type="module">`);}
function injectBeforeBodyEnd(html,scripts,label){if(!/<\/body>/i.test(html))throw new Error(`${label} has no body end`);return html.replace(/<\/body>/i,`${scripts.join("\n")}\n</body>`);}
await rm(dist,{recursive:true,force:true});await mkdir(dist,{recursive:true});for(const directory of["apps","shared","content"])await cp(join(root,directory),join(dist,directory),{recursive:true});const runtimeScripts=['<script src="/shared/web.js" defer></script>','<script src="/shared/wasm.js" defer></script>'].join("\n    ");
for(const app of["site","docs","lib","api","graph","worlds","platform","ide"]){const path=join(dist,"apps",app,"index.html");let html=await readFile(path,"utf8");if(!html.includes("/shared/web.js"))html=html.replace(/<head([^>]*)>/i,`<head$1>\n    <!-- idol runtime -->\n    ${runtimeScripts}`);if(app==="platform"&&!html.includes("/shared/platform-ide-entry.js"))html=injectBeforeBodyEnd(html,['<script src="/shared/platform-ide-entry.js"></script>'],"Platform");if(app==="ide"&&!html.includes("/shared/ide-semantic-layer.js"))html=injectBeforeModule(html,['<script src="/shared/ide-semantic-layer.js"></script>','<script src="/shared/ide-directory.js"></script>'],"IDE");await writeFile(path,html);}
await mkdir(join(dist,"runtime"),{recursive:true});await cp(join(root,"runtime","worlds.json"),join(dist,"runtime","worlds.json"));const foreignSource=validateForeignSource(JSON.parse(await readFile(join(root,"content","foreign.json"),"utf8")));const foreignManifest={schema:"idol.web.foreign.v1",revision:foreignSource.revision,authority:{language:{repository:authorityPin.language.repository,commit:authority},native:{repository:authorityPin.native.repository,commit:native}},worlds:foreignSource.worlds,import_kinds:foreignSource.import_kinds};await writeFile(join(dist,"runtime","foreign.json"),`${JSON.stringify(foreignManifest,null,2)}\n`);
const configured=process.env.IDOL_WASM_PATH?resolve(process.env.IDOL_WASM_PATH):join(root,"runtime","idol-web.wasm");let wasm={available:false,file:null,bytes:0,sha256:null};if(await exists(configured)){const target=join(dist,"runtime","idol-web.wasm");await cp(configured,target);const content=await readFile(target);wasm={available:true,file:"/runtime/idol-web.wasm",bytes:(await stat(target)).size,sha256:createHash("sha256").update(content).digest("hex")};}
const ide={route:"https://platform.idol.id/ide",local_storage:"indexeddb",source_upload:"explicit-remote-analysis-only",remote_analysis:"/v1/ide/analyze",browser_wasm:wasm.available};const runtimeManifest={schema:"idol.web.runtime.v1",authority:{repository:"clpi/idol",commit:authority},native:{repository:"clpi/idol-native",commit:native},bridge:"/shared/web.js",worlds:"/runtime/worlds.json",foreign:"/runtime/foreign.json",wasm,ide,note:wasm.available?"Idol Wasm artifact is deployed and loaded as the preferred compute realization.":"The semantic web bridge is active; provide IDOL_WASM_PATH when the canonical Idol browser artifact is admitted."};await writeFile(join(dist,"runtime","manifest.json"),`${JSON.stringify(runtimeManifest,null,2)}\n`);const manifest={schema:"idol.web.deploy.v1",commit,authority,surfaces:{"idol.id":"site","docs.idol.id":"docs","lib.idol.id":"lib","api.idol.id":"api","graph.idol.id":"graph","worlds.idol.id":"worlds","platform.idol.id":"platform","r8a.idol.id":"graph:r8a","r8b.idol.id":"graph:r8b","r16.idol.id":"graph:r16"},runtime:runtimeManifest};await writeFile(join(dist,"manifest.json"),`${JSON.stringify(manifest,null,2)}\n`);console.log(`built ${Object.keys(manifest.surfaces).length} idol.id surfaces plus the protected IDE at ${commit}`);console.log(`foreign candidates: ${foreignManifest.worlds.length} · revision ${foreignManifest.revision}`);console.log(`idol wasm: ${wasm.available?`${wasm.bytes} bytes ${wasm.sha256}`:"not supplied (bridge remains explicit)"}`);
